config/routes.rb
Rails.application.routes.draw do
  devise_for :trainers
  devise_for :clients
  root 'static_pages#home'
  resources :events
  
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
  	has_attached_file :confirm, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :confirm, content_type: /\Aimage\/.*\Z/
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def new
		@event = Event.new
	end

	def create
		@event = Event.new(permit_event)
		@event.save
		redirect_to event_path(@event)
	end

	def show
		@event = Event.find(params[:id])
	end

	private

		def permit_event
			params.require(:event).permit(:title, :description, :price, :time, :cover, :confirm)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/index.html.erb
<div class="main-wrap">
	<!-- <input id="slide-sidebar" type="checkbox" role="button" />
        <label for="slide-sidebar"><span><img src="/assets/Dash icon.png" class="menudash" alt=""></span></label> -->
	
	<div class="trainerpages">
		<div class="trainerheader">
			<img src="/assets/Dash icon.png" class="menudash" alt="">
			<ul class="trainheadmenu">
				<li><a href="#">FAQ</a></li>
				<li><a href="#">LOG OUT</a></li>
			</ul>
		</div>
		<div class="traintitle">
			<p>My Classes</p>
		</div>
	</div>
	
</div>

app/views/events/new.html.erb
<div class="main-wrap">
	<!-- <input id="slide-sidebar" type="checkbox" role="button" />
        <label for="slide-sidebar"><span><img src="/assets/Dash icon.png" class="menudash" alt=""></span></label> -->
	
	<div class="trainerpages">
		<div class="trainerheader">
			<a href="#menu-toggle" id="menu-toggle"><img src="/assets/Dash icon.png" alt=""></a>
			<ul class="trainheadmenu">
				<li><a href="#">FAQ</a></li>
				<li><a href="#">LOG OUT</a></li>
			</ul>
		</div>
		<div class="traintitle">
			<p>Create a Class</p>
		</div>
		<div class="page">

			<div class="pagetitle">
				<h4>Upload Photos</h4>
			</div>
			<div class="photo">
				<div class="well photobox text-center">
					<img src="/assets/camera.png" alt="camera icon">
					<p>cover photo</p>
					<p>(750 x 450)</p>
				</div>
				<div class="photoboxtext">
					<p><span>Hint:</span> Make this photo enticing, it will be the first thing your clients see while searching for classes.</p>
				</div>
				<div class="well photobox text-center">
					<img src="/assets/camera.png" alt="camera icon">
					<p>confirmation photo</p>
					<p>(750 x 600)</p>
				</div>
				<div class="photoboxtext">
					<p><span>Hint:</span> This photo will thank your clients for their business.  It should leave them excited for the upcoming class.</p>
				</div>
			</div>
			<div class="break"></div>
			<%= form_for @event, html: {class: 'classform', multipart: true} do |f| %>
				<div class="leftside">
					<div class="pagetitle">
						<h4>Class Details</h4>
					</div>
					<%= f.text_field :title, placeholder: "Title of Class" %>
					<%= text_field_tag :location, nil, placeholder: "Location" %>
					<div>
						<%= f.text_area :description, placeholder: "Describe your class and get your client base excited to sign-up" %>
						<span class="expaliner">Description</span>
					</div>
					<div>
						<%= f.text_field :price, placeholder: "$0.00" %>
						<span class="expaliner">Price</span>
					</div>
					
				</div>
				<div class="rightside">
					<div class="pagetitle">
						<h4>Extra Details (Optional)</h4>
					</div>
						<p>
							<%= f.file_field :cover %>
						</p>
						<p>
							<%= f.file_field :confirm %>
						</p>
					<div>
						<%= text_area_tag :tips, nil, placeholder: "Instructions and equipment necessary to attend (seperated by commas)", class: "secondtext" %>
						<span class="explainer">Tips</span>
					</div>
					<div>
						<%= text_area_tag :tags, nil, placeholder: "Describe your class and get your client base excited to sign-up", class: "secondtext" %>
						<span class="explainer">Tags</span>
					</div>
					<div class="terms">
        				By clicking publish you agree to our 
        				<a href="#">
          					terms of service 
        				</a>
      				</div>
      				<%= f.submit "Submit", class: "butt" %>
				</div>
			<% end %>	
		</div>
	</div>
	
</div>

app/views/events/payment.html.erb
<div class="main-wrap">
	<input id="slide-sidebar" type="checkbox" role="button" />
        <label for="slide-sidebar"><span><img src="/assets/Dash icon.png" class="menudash" alt=""></span></label>
	<div class="sidebar">
		<!-- <div class="sidebartitlebox">
			
		</div> -->
		<div class="sidebarbody">
			<div class="sidebartitle">
				<h3>FIT</h3>
				<p>TRAINER</p>
			</div>
			<div class="sideimage">
				<img src="/assets/me.jpg" alt="">
				<p>Bobby Glaze</p>
			</div>
			<ul class="sidebarmenu">
				<li><a href="#">Create Class</a></li>
				<li><a href="#">My Classes</a></li>
				<li><a href="#">Profile</a></li>
				<li><a href="#">Payment Info</a></li>
				<li><a href="#">Stats</a></li>
			</ul>
			<div class="sidefooter">
				<div class="sidefootercontent">
					<h3>FIT</h3>
	      			<p>&copy FIT app. All rights reserved</p>
	      		</div>
			</div>	
		</div>
		
	</div>

	<div class="trainerpages">
		<div class="trainerheader">
			<ul>
				<li><a href="#">FAQ</a></li>
				<li><a href="#">LOG OUT</a></li>
			</ul>
		</div>
		<div class="traintitle">
			<p>Payment Information</p>
		</div>
	</div>
	<div class="test">test</div>
</div>

app/views/events/profile.html.erb
<div class="main-wrap">
	<input id="slide-sidebar" type="checkbox" role="button" />
        <label for="slide-sidebar"><span><img src="/assets/Dash icon.png" class="menudash" alt=""></span></label>
	<div class="sidebar">
		<!-- <div class="sidebartitlebox">
			
		</div> -->
		<div class="sidebarbody">
			<div class="sidebartitle">
				<h3>FIT</h3>
				<p>TRAINER</p>
			</div>
			<div class="sideimage">
				<img src="/assets/me.jpg" alt="">
				<p>Bobby Glaze</p>
			</div>
			<ul class="sidebarmenu">
				<li><a href="#">Create Class</a></li>
				<li><a href="#">My Classes</a></li>
				<li><a href="#">Profile</a></li>
				<li><a href="#">Payment Info</a></li>
				<li><a href="#">Stats</a></li>
			</ul>
			<div class="sidefooter">
				<div class="sidefootercontent">
					<h3>FIT</h3>
	      			<p>&copy FIT app. All rights reserved</p>
	      		</div>
			</div>	
		</div>
		
	</div>

	<div class="trainerpages">
		<div class="trainerheader">
			<ul>
				<li><a href="#">FAQ</a></li>
				<li><a href="#">LOG OUT</a></li>
			</ul>
		</div>
		<div class="traintitle">
			<p>Edit Profile</p>
		</div>
	</div>
	<div class="test">test</div>
</div>

app/views/events/show.html.erb
<h1 class="show"><%= @event.title %></h1>

<%= image_tag @event.confirm.url, class: 'pic' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper">
		<div class="sidebar">
			<div class="sidebarbody">
				<div class="sidebartitle">
					<h3>FIT</h3>
					<p>TRAINER</p>
				</div>
				<div class="sideimage">
					<img src="/assets/me.jpg" alt="">
					<p>Bobby Glaze</p>
				</div>
				<ul class="sidebarmenu">
					<%= link_to new_event_path do %>
						<li>Create Class</li>
					<% end %>
					<%= link_to events_path do %>
						<li>My Classes</li>
					<% end %>
					<a href="#"><li>Profile</li></a>
					<a href="#"><li>Payment Info</li></a>
					<a href="#"><li>Stats</li></a>
				</ul>
				<div class="sidefooter">
					<div class="sidefootercontent">
						<h3>FIT</h3>
		      			<p>&copy FIT app. All rights reserved</p>
		      		</div>
				</div>	
			</div>
			
		</div>
	</div>	
<%= yield %>
	
	<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>Home</h1>